"""add knowledge chunk embedding identity

Revision ID: 09ca4171d024
Revises: b633cf8aa666
Create Date: 2026-08-12 13:11:50.846245

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09ca4171d024'
down_revision: Union[str, Sequence[str], None] = 'b633cf8aa666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_chunks', sa.Column('embedding_model', sa.String(length=120), nullable=True))
    op.add_column('knowledge_chunks', sa.Column('embedding_key', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_chunks', 'embedding_key')
    op.drop_column('knowledge_chunks', 'embedding_model')
    # ### end Alembic commands ###
