"""add gmail command idempotency

Revision ID: 0df91a709e4a
Revises: 834c89f3896f
Create Date: 2026-08-16 18:49:28.550884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0df91a709e4a'
down_revision: Union[str, Sequence[str], None] = '834c89f3896f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_commands',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('reply_draft_id', sa.Uuid(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reply_draft_id'], ['reply_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'idempotency_key', name='uq_gmail_commands_user_id_idempotency_key')
    )
    op.create_index(op.f('ix_gmail_commands_reply_draft_id'), 'gmail_commands', ['reply_draft_id'], unique=False)
    op.create_index(op.f('ix_gmail_commands_state'), 'gmail_commands', ['state'], unique=False)
    op.create_index(op.f('ix_gmail_commands_user_id'), 'gmail_commands', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gmail_commands_user_id'), table_name='gmail_commands')
    op.drop_index(op.f('ix_gmail_commands_state'), table_name='gmail_commands')
    op.drop_index(op.f('ix_gmail_commands_reply_draft_id'), table_name='gmail_commands')
    op.drop_table('gmail_commands')
    # ### end Alembic commands ###
