"""add reply draft audit events

Revision ID: 1040ba9a2625
Revises: a76378a27408
Create Date: 2026-08-08 19:58:28.144099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1040ba9a2625'
down_revision: Union[str, Sequence[str], None] = 'a76378a27408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reply_draft_audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reply_draft_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=True),
    sa.Column('actor_user_id', sa.Uuid(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reply_draft_id'], ['reply_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reply_draft_audit_events_reply_draft_id'), 'reply_draft_audit_events', ['reply_draft_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reply_draft_audit_events_reply_draft_id'), table_name='reply_draft_audit_events')
    op.drop_table('reply_draft_audit_events')
    # ### end Alembic commands ###
