"""add execution idempotency fields

Revision ID: 3c3984105222
Revises: e3a13db12d7c
Create Date: 2026-07-29 19:27:17.306378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c3984105222'
down_revision: Union[str, Sequence[str], None] = 'e3a13db12d7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Add execution idempotency fields safely."""

    # Step 1: Add the columns as nullable for existing rows.
    op.add_column(
        "executions",
        sa.Column(
            "idempotency_key",
            sa.String(length=255),
            nullable=True,
        ),
    )

    op.add_column(
        "executions",
        sa.Column(
            "input_hash",
            sa.String(length=64),
            nullable=True,
        ),
    )

    # Step 2: Backfill existing execution rows.
    op.execute(
        """
        UPDATE executions
        SET idempotency_key = 'legacy-' || CAST(id AS TEXT)
        WHERE idempotency_key IS NULL
        """
    )

    op.execute(
        """
        UPDATE executions
        SET input_hash =
            '0000000000000000000000000000000000000000000000000000000000000000'
        WHERE input_hash IS NULL
        """
    )

    # Step 3: Make both columns required.
    op.alter_column(
        "executions",
        "idempotency_key",
        existing_type=sa.String(length=255),
        nullable=False,
    )

    op.alter_column(
        "executions",
        "input_hash",
        existing_type=sa.String(length=64),
        nullable=False,
    )

    # Step 4: Enforce uniqueness per workflow.
    op.create_unique_constraint(
        "uq_executions_workflow_id_idempotency_key",
        "executions",
        ["workflow_id", "idempotency_key"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_executions_workflow_id_idempotency_key', 'executions', type_='unique')
    op.drop_column('executions', 'input_hash')
    op.drop_column('executions', 'idempotency_key')
    # ### end Alembic commands ###
