"""add knowledge chunk embedding

Revision ID: 7ee9ac9f7665
Revises: f9ede2d922f9
Create Date: 2026-08-11 13:47:42.022496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR


# revision identifiers, used by Alembic.
revision: str = '7ee9ac9f7665'
down_revision: Union[str, Sequence[str], None] = 'f9ede2d922f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "knowledge_chunks",
        sa.Column("embedding", VECTOR(dim=1536), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_chunks', 'embedding')
    # ### end Alembic commands ###
