"""add knowledge document storage key

Revision ID: 86336d10141a
Revises: 011a8242d667
Create Date: 2026-08-11 20:01:05.978114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86336d10141a'
down_revision: Union[str, Sequence[str], None] = '011a8242d667'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'knowledge_documents',
        sa.Column('storage_key', sa.String(length=512), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_documents', 'storage_key')
    # ### end Alembic commands ###