"""add workflow steps and step runs

Revision ID: 95f01d13255e
Revises: f92d24b07452
Create Date: 2026-07-22 14:30:03.083778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95f01d13255e'
down_revision: Union[str, Sequence[str], None] = 'f92d24b07452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.Uuid(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_id'], ['workflows.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_id', 'position', name='uq_workflow_step_position')
    )
    op.create_index(op.f('ix_workflow_steps_workflow_id'), 'workflow_steps', ['workflow_id'], unique=False)
    op.create_table('step_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_step_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'completed', 'failed', name='step_run_status'), nullable=False),
    sa.Column('input_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('output_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workflow_step_id'], ['workflow_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_step_runs_execution_id'), 'step_runs', ['execution_id'], unique=False)
    op.create_index(op.f('ix_step_runs_workflow_step_id'), 'step_runs', ['workflow_step_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index(
        op.f("ix_step_runs_workflow_step_id"),
        table_name="step_runs",
    )

    op.drop_index(
        op.f("ix_step_runs_execution_id"),
        table_name="step_runs",
    )

    op.drop_table("step_runs")

    sa.Enum(
        name="step_run_status",
    ).drop(
        op.get_bind(),
        checkfirst=True,
    )

    op.drop_index(
        op.f("ix_workflow_steps_workflow_id"),
        table_name="workflow_steps",
    )

    op.drop_table("workflow_steps")