"""add gmail watch state

Revision ID: 978757cd56b4
Revises: 1040ba9a2625
Create Date: 2026-08-09 13:13:47.411372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '978757cd56b4'
down_revision: Union[str, Sequence[str], None] = '1040ba9a2625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_connections', sa.Column('gmail_history_id', sa.String(length=255), nullable=True))
    op.add_column('oauth_connections', sa.Column('gmail_watch_expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_connections', 'gmail_watch_expires_at')
    op.drop_column('oauth_connections', 'gmail_history_id')
    # ### end Alembic commands ###
