"""add gmail message proof

Revision ID: a76378a27408
Revises: ca815c053963
Create Date: 2026-08-08 19:45:19.689946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a76378a27408'
down_revision: Union[str, Sequence[str], None] = 'ca815c053963'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reply_drafts', sa.Column('gmail_message_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reply_drafts', 'gmail_message_id')
    # ### end Alembic commands ###
