"""add extracted text to knowledge documents

Revision ID: b633cf8aa666
Revises: c1f4de3aaa1a
Create Date: 2026-08-12 12:15:21.537320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b633cf8aa666'
down_revision: Union[str, Sequence[str], None] = 'c1f4de3aaa1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_documents', 'extracted_text')
    # ### end Alembic commands ###
