"""add chunk version to knowledge chunks

Revision ID: c1f4de3aaa1a
Revises: dec4716250d7
Create Date: 2026-08-12 11:59:19.103696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1f4de3aaa1a'
down_revision: Union[str, Sequence[str], None] = 'dec4716250d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_chunks', sa.Column('chunk_version', sa.String(length=12), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('knowledge_chunks', 'chunk_version')
    # ### end Alembic commands ###
