"""add execution events

Revision ID: e3a13db12d7c
Revises: 0c06a8f877b9
Create Date: 2026-07-29 15:26:00.011102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3a13db12d7c'
down_revision: Union[str, Sequence[str], None] = '0c06a8f877b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_events_correlation_id'), 'execution_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_execution_events_event_type'), 'execution_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_execution_events_execution_id'), 'execution_events', ['execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_events_execution_id'), table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_event_type'), table_name='execution_events')
    op.drop_index(op.f('ix_execution_events_correlation_id'), table_name='execution_events')
    op.drop_table('execution_events')
    # ### end Alembic commands ###
