"""associate oauth connections with workflows

Revision ID: f0635078189f
Revises: 978757cd56b4
Create Date: 2026-08-09 13:46:46.878144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0635078189f'
down_revision: Union[str, Sequence[str], None] = '978757cd56b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_connections', sa.Column('workflow_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_oauth_connections_workflow_id'), 'oauth_connections', ['workflow_id'], unique=False)
    op.create_foreign_key(None, 'oauth_connections', 'workflows', ['workflow_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'oauth_connections', type_='foreignkey')
    op.drop_index(op.f('ix_oauth_connections_workflow_id'), table_name='oauth_connections')
    op.drop_column('oauth_connections', 'workflow_id')
    # ### end Alembic commands ###
