"""add gmail messages

Revision ID: fbbe9329ef95
Revises: f0635078189f
Create Date: 2026-08-09 15:24:33.224324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbbe9329ef95'
down_revision: Union[str, Sequence[str], None] = 'f0635078189f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gmail_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=False),
    sa.Column('provider_thread_id', sa.String(length=255), nullable=True),
    sa.Column('sender', sa.Text(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('body_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'provider_message_id', name='uq_gmail_messages_user_provider_message')
    )
    op.create_index(op.f('ix_gmail_messages_user_id'), 'gmail_messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gmail_messages_user_id'), table_name='gmail_messages')
    op.drop_table('gmail_messages')
    # ### end Alembic commands ###
